import type { Metadata, Viewport } from 'next'
import { Inter, Instrument_Serif, Space_Grotesk, JetBrains_Mono } from 'next/font/google'
import './globals.css'
import { BRAND } from '@/config/brand'
import { ToastProvider } from '@/components/ui/Toast'
import PWAInstallPrompt from '@/components/pwa/PWAInstallPrompt'
import { I18nProvider } from '@/components/I18nProvider'
import Footer from '@/components/Footer'
import { FeeConfigProvider } from '@/components/FeeConfigProvider'
import SmoothScroll from '@/components/SmoothScroll'
import { getPlatformFeeSettings } from '@/lib/checkout/fee-config-server'
import { cookies, headers } from 'next/headers'

// Resolve the reader's language on the server: the i18nextLng cookie (written
// by the client detector on every language change) wins; a first-time visitor
// falls back to Accept-Language; anything else is English. This is what lets
// SSR speak fr/ht from the first byte instead of flashing English.
async function resolveLanguage(): Promise<'en' | 'fr' | 'ht'> {
  const supported = ['en', 'fr', 'ht'] as const
  const fromCookie = (await cookies()).get('i18nextLng')?.value?.slice(0, 2)
  if (supported.includes(fromCookie as any)) return fromCookie as any
  const accept = (await headers()).get('accept-language') || ''
  for (const part of accept.split(',')) {
    const code = part.trim().slice(0, 2).toLowerCase()
    if (supported.includes(code as any)) return code as any
  }
  return 'en'
}

// Body / UI typeface
const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
  display: 'swap',
})

// Editorial display typeface (headlines, wordmark) — gives the public site its poster feel
const instrumentSerif = Instrument_Serif({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-serif-display',
  display: 'swap',
})

// Mono-ish grotesk for buttons, nav and dense UI
const spaceGrotesk = Space_Grotesk({
  subsets: ['latin'],
  weight: ['500', '600', '700'],
  variable: '--font-grotesk',
  display: 'swap',
})

// Technical layer — monospace for eyebrows, dates, prices-as-data and ticket IDs
const jetBrainsMono = JetBrains_Mono({
  subsets: ['latin'],
  weight: ['500', '600'],
  variable: '--font-mono',
  display: 'swap',
})

const siteUrl = process.env.NEXT_PUBLIC_APP_URL || 'https://tikem.co'
const siteDescription = `Discover and buy tickets for events in Haiti - ${BRAND.name}`

export const metadata: Metadata = {
  metadataBase: new URL(siteUrl),
  title: BRAND.name,
  description: siteDescription,
  applicationName: BRAND.name,
  manifest: '/manifest.json',
  icons: {
    // Adaptive SVG favicon: transparent — the glyph flips for contrast, no tile.
    // ?v=2 busts browsers' per-origin favicon caches still holding the old tile.
    // favicon.ico is the fallback for clients that skip SVG (and the path
    // crawlers request blind); generated by scripts/generate-raster-icons.mjs.
    icon: [
      { url: '/favicon.svg?v=2', type: 'image/svg+xml' },
      { url: '/favicon.ico', sizes: '32x32' },
    ],
    // Apple home-screen icon must be opaque on any wallpaper — the fixed dark
    // tile, as a 180x180 PNG: iOS ignores SVG touch icons.
    apple: [{ url: '/apple-touch-icon.png', sizes: '180x180', type: 'image/png' }],
  },
  openGraph: {
    type: 'website',
    siteName: BRAND.name,
    title: BRAND.name,
    description: siteDescription,
    url: siteUrl,
    locale: 'en_US',
    images: [
      {
        url: '/og-image.png',
        width: 1200,
        height: 630,
        alt: `${BRAND.name}, ${BRAND.tagline ?? 'Discover Events in Haiti'}`,
      },
    ],
  },
  twitter: {
    card: 'summary_large_image',
    title: BRAND.name,
    description: siteDescription,
    images: ['/og-image.png'],
  },
  appleWebApp: {
    capable: true,
    statusBarStyle: 'default',
    title: BRAND.name,
  },
  other: {
    'mobile-web-app-capable': 'yes',
  },
}

export const viewport: Viewport = {
  themeColor: '#0F766E',
  width: 'device-width',
  initialScale: 1,
  maximumScale: 5,
  userScalable: true,
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  // The fee rates in force, read once per render and seeded
  // into the pricing layer below. This is what keeps an advertised price honest
  // after an admin edits the rate: without it, every displayed total would be
  // computed from the compiled-in defaults while checkout charged the new figure.
  // A settings read must never take the whole site down, so a failure falls back
  // to the defaults — the same values the code shipped with.
  const feeConfig = await getPlatformFeeSettings()
  const lng = await resolveLanguage()

  return (
    <html lang={lng} className={`${inter.variable} ${instrumentSerif.variable} ${spaceGrotesk.variable} ${jetBrainsMono.variable}`}>
      <head>
        {/* DNS Prefetch for faster external resource loading */}
        <link rel="dns-prefetch" href="https://firebasestorage.googleapis.com" />
        <link rel="dns-prefetch" href="https://api.stripe.com" />
        <link rel="dns-prefetch" href="https://api.resend.com" />
        {/* Preconnect for critical resources */}
        <link rel="preconnect" href="https://firebasestorage.googleapis.com" crossOrigin="anonymous" />
        <link rel="preconnect" href="https://api.stripe.com" crossOrigin="anonymous" />
      </head>
      {/*
        A COLUMN THAT FILLS THE VIEWPORT. The footer is rendered after every
        page, so on a short page, or one that errors into near-empty content, 
        it floated wherever the content stopped, leaving a large dead band of
        background beneath it on mobile. min-h-dvh (not vh: iOS Safari's toolbar
        makes vh taller than the visible area) plus flex-1 on the content pushes
        the footer to the bottom where it belongs.
      */}
      <body className={inter.className + ' mobile-typography min-h-dvh flex flex-col'}>
        {/* Lenis inertial scroll on public surfaces (no-op on consoles/flows). */}
        <SmoothScroll />
        <FeeConfigProvider config={feeConfig}>
          <I18nProvider lng={lng}>
            <ToastProvider>
              <div className="flex-1">{children}</div>
              <Footer />
            </ToastProvider>
            <PWAInstallPrompt />
          </I18nProvider>
        </FeeConfigProvider>
      </body>
    </html>
  )
}
